server:
  port: 8088
spring:
  application:
    name: winrpc-demo-consumer
winrpc:
  zk:
    server: localhost:2181
    root: winrpc
  app:
    id: app1
    namespace: public
    env: dev
  consumer:
    retries: 2
    timeout: 1000
    grayRatio: 33 # 0-100
    faultLimit: 10 # 30s 内10次错误则隔离
    halfOpenInitialDelay: 10000
    halfOpenDelay: 60000

winregistry:
  servers: http://localhost:8484

app:
  id: app1
#apollo:
#  cacheDir: /opt/data/
#  cluster: default
#  meta: http://localhost:8080
#  autoUpdateInjectedSpringProperties: true
#  bootstrap:
#    enabled: true
#    namespaces: app1
#    eagerLoad:
#      enabled: false

logging:
  level:
    root: error
    cn.winwang.winrpc: debug