server:
  port: 8088
spring:
  application:
    name: winrpc-demo-consumer
winrpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2181
  zkRoot: winrpc

app:
  id: app1
  namespace: public
  env: dev
  retries: 2
  timeout: 1000
  grayRatio: 10 # 流量百分比 0-100

logging:
  level:
    root: error
    cn.winwang.winrpc: debug