spring:
  application:
    name: winrpc-demo-provider
server:
  port: 8081

winrpc:
  zk:
    server: localhost:2181
    root: winrpc
    app:
      id: app1
      namespace: public
      env: dev
    provider:
      metas:
        dc: bj
        gray: false
        unit: B001
        tc: 25

logging:
  level:
    root: error
    cn.winwang.winrpc: info