spring:
  application:
    name: winrpc-demo-provider
server:
  port: 8081

winrpc:
  zkServer: localhost:2181
  zkRoot: winrpc

app:
  id: app1
  namespace: public
  env: dev

logging:
  level:
    root: error
    cn.winwang.winrpc: info